// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYAWWkDOW54MfZFkFxVUyrr3yMCJpIlPo',
    appId: '1:886948364149:web:5ddb57a30bd0faf1de9d3c',
    messagingSenderId: '886948364149',
    projectId: 'elder-care-companion-app-0303',
    authDomain: 'elder-care-companion-app-0303.firebaseapp.com',
    storageBucket: 'elder-care-companion-app-0303.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsh75-IFxOtnWRJyTEnThPXBhkwQmRAlI',
    appId: '1:886948364149:android:0cbefa698dd55de6de9d3c',
    messagingSenderId: '886948364149',
    projectId: 'elder-care-companion-app-0303',
    storageBucket: 'elder-care-companion-app-0303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVF9fjxG8vhlx0ymZRmMoK0gQcLntfcc',
    appId: '1:886948364149:ios:b985d2ffcfb1798bde9d3c',
    messagingSenderId: '886948364149',
    projectId: 'elder-care-companion-app-0303',
    storageBucket: 'elder-care-companion-app-0303.firebasestorage.app',
    iosBundleId: 'com.example.eccapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCVF9fjxG8vhlx0ymZRmMoK0gQcLntfcc',
    appId: '1:886948364149:ios:b985d2ffcfb1798bde9d3c',
    messagingSenderId: '886948364149',
    projectId: 'elder-care-companion-app-0303',
    storageBucket: 'elder-care-companion-app-0303.firebasestorage.app',
    iosBundleId: 'com.example.eccapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYAWWkDOW54MfZFkFxVUyrr3yMCJpIlPo',
    appId: '1:886948364149:web:133c786f37b0c962de9d3c',
    messagingSenderId: '886948364149',
    projectId: 'elder-care-companion-app-0303',
    authDomain: 'elder-care-companion-app-0303.firebaseapp.com',
    storageBucket: 'elder-care-companion-app-0303.firebasestorage.app',
  );
}
